---
- name: Cloning Swallow source repository for development
  git:
    repo: "{{ swallow_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ swallow_dev_repos_pull }}"
    version: "{{ swallow_source_version }}"
