---
- name: Enable mariadb bundle resource in pacemaker
  command: >
    docker exec hacluster_pacemaker pcs resource enable mariadb-bundle
  run_once: True

- name: Enable mariadb clustercheck bundle resource in pacemaker
  command: >
    docker exec hacluster_pacemaker pcs resource enable mariadb-clustercheck-bundle
  run_once: True
