---
- name: Set mariadb pcs resource force updated
  set_fact:
    mariadb_force_update: 'yes'

- import_tasks: deploy.yml

- name: Run upgrade in MariaDB container
  become: true
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    detach: False
    dimensions: "{{ default_container_dimensions }}"
    environment:
      KOLLA_UPGRADE:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      DB_HOST: "{{ api_interface_address }}"
      DB_PORT: "{{ mariadb_port }}"
      DB_ROOT_PASSWORD: "{{ database_password }}"
    image: "{{ mariadb_image }}:{{ mariadb_tag }}"
    labels:
      UPGRADE:
    name: "upgrade_mariadb"
    restart_policy: no
  run_once: true
  no_log: true
