---
- name: Cloning goering source repository for development
  git:
    repo: "{{ goering_git_repository }}"
    dest: "{{ kolla_dev_repos_directory }}/{{ project_name }}"
    update: "{{ goering_dev_repos_pull }}"
    version: "{{ goering_source_version }}"
