---
- include_tasks: register.yml
  when: inventory_hostname in groups['goering-api']

- include_tasks: config.yml
  when: inventory_hostname in groups['goering-api'] or
        inventory_hostname in groups['goering-processor']

- import_tasks: check-containers.yml

- include_tasks: clone.yml
  when: goering_dev_mode | bool

- include_tasks: bootstrap.yml
  when: inventory_hostname in groups['goering-api']

- name: Flush handlers
  meta: flush_handlers
