---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - goering_api
  register: container_facts

- name: Checking free port for Goering API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ goering_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['goering_api'] is not defined
    - inventory_hostname in groups['goering-api']
