---
- name: Get container facts
  become: true
  kolla_container_facts:
    name:
      - juggernaut_api
  register: container_facts

- name: Checking free port for Juggernaut API
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ juggernaut_api_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['juggernaut_api'] is not defined
    - inventory_hostname in groups['juggernaut-api']
