{
 "title": "Redis Cluster",
 "tags": [ "redis exporter" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "数据源", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "服务运行时间",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "redis_uptime_in_seconds" }
   ]
  },
  {
   "title": "客户端连接数",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "命令执行速率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "redis_keyspace_hits_total/(redis_keyspace_hits_total+redis_keyspace_misses_total)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "实例内存使用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_bytes ", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "网络带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[5m])",
     "legendFormat": "{{instance}}_input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total[5m])",
     "legendFormat": "{{instance}}_output"
    }
   ]
  }
 ]
}