{
 "title": "Prometheus Server",
 "tags": [
  "prometheus",
  "prometheus server"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "数据源", "query": "prometheus" },
   {
    "name": "instance",
    "label": "主机",
    "query": "label_values(prometheus_build_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "sample"
    }
   ]
  },
  {
   "title": "Scrape Duration - Top 3",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(3, max(scrape_duration_seconds) by (job,instance))",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{instance=~\"$instance\"})",
     "legendFormat": "active appenders"
    },
    {
     "expr": "sum(process_open_fds{instance=~\"$instance\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "WAL Completed Pages",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_completed_pages_total{instance=~\"$instance\"}",
     "legendFormat": "page"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{instance=~\"$instance\"}",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{instance=~\"$instance\"}",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{instance=~\"$instance\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=~\"prometheus\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{instance=~\"$instance\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{instance=~\"$instance\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "missed"
    },
    {
     "expr": "rate(prometheus_rule_group_iterations_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "iterations"
    }
   ]
  }
 ]
}