{
 "title": "HAProxy Stats",
 "tags": [ "haproxy exporter" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "数据源", "query": "prometheus" },
   {
    "name": "instance",
    "label": "主机",
    "query": "label_values(haproxy_up,instance)"
   },
   {
    "name": "frontend",
    "label": "前端服务",
    "query": "label_values(haproxy_frontend_sessions_total, frontend)"
   },
   {
    "name": "backend",
    "label": "后端服务",
    "query": "label_values(haproxy_backend_sessions_total, backend)"
   },
   {
    "name": "code",
    "label": "HTTP 状态码",
    "query": "label_values(haproxy_frontend_http_responses_total{frontend=~'$frontend'}, code)"
   }
  ]
 },
 "panels": [
  {
   "title": "Frontend Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend HTTP Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_requests_total{frontend=~'$frontend'}[5m])) by (frontend)",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Frontend HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_http_responses_total{frontend=~'$frontend', code=~'$code'}[5m])) by (frontend,code)",
       "legendFormat": "{{ frontend }}_{{ code }}"
      }
     ]
    },
    {
     "title": "Frontend Request Errors & Denied",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(irate(haproxy_frontend_request_errors_total{frontend=~'$frontend'}[5m])) by (frontend)",
       "legendFormat": "{{frontend}}_errors"
      },
      {
       "expr": "sum(irate(haproxy_frontend_requests_denied_total{frontend=~'$frontend'}[5m])) by (frontend)",
       "legendFormat": "{{frontend}}_denied"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend HTTP Responses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_http_responses_total{instance=~'$instance',backend=~'$backend',code=~'$code'}[5m])",
       "legendFormat": "{{instance}}_{{backend}}_{{code}}"
      }
     ]
    },
    {
     "title": "Backend Response Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_response_errors_total{backend=~'$backend'}[5m])",
       "legendFormat": "{{instance}}_{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "前端服务带宽",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "Bps", "label": "OUT（-）/ IN（+）" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_frontend_bytes_in_total{frontend=~'$frontend'}[5m])",
       "legendFormat": "{{frontend}}_IN"
      },
      {
       "expr": "irate(haproxy_frontend_bytes_out_total{frontend=~'$frontend'}[5m])",
       "legendFormat": "{{frontend}}_OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "后端服务带宽",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "Bps", "label": "OUT（-）/ IN（+）" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_bytes_in_total{backend=~'$backend'}[5m])",
       "legendFormat": "{{instance}}_{{backend}}_IN"
      },
      {
       "expr": "irate(haproxy_backend_bytes_out_total{backend=~'$backend'}[5m])",
       "legendFormat": "{{instance}}_{{backend}}_OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Current Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_current_sessions{frontend=~'$frontend'}",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Frontend New Session Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_current_session_rate{frontend=~'$frontend'}",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Frontend Max Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{frontend=~'$frontend'}",
       "legendFormat": "{{frontend}}"
      }
     ]
    },
    {
     "title": "Frontend Max Session Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{frontend=~'$frontend'}",
       "legendFormat": "{{frontend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Current Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_sessions{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    },
    {
     "title": "Backend New Session Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_sessions{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    },
    {
     "title": "Backend Max Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 110 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_sessions{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    },
    {
     "title": "Backend Max Session Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_sessions{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Connection Errors Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(haproxy_backend_connection_errors_total{backend=~'$backend'}[5m])",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backend Current Queue Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_current_queue{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    },
    {
     "title": "Backend Max Queue Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "haproxy_backend_max_queue{backend=~'$backend'}",
       "legendFormat": "{{instance}}_{{backend}}"
      }
     ]
    }
   ]
  }
 ]
}