---
- name: Restart ryze container
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
    ryze_container: "{{ check_ryze_containers.results|selectattr('item.key', 'equalto', service_name)|first }}"
  become: true
  kolla_docker:
    action: "recreate_or_restart_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    dimensions: "{{ service.dimensions }}"
  when:
    - kolla_action != "config"
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - ryze_conf.changed | bool
      or ryze_config_json.changed | bool
      or ryze_container.changed | bool
