---
- name: Set node_custom_config to be kolla
  set_fact:
    node_custom_config: "/etc/kolla/config"
  when: inventory_hostname in groups['neutron-uplugin-agent']

- name: Ensure neutron-uplugin-agent directory is present
  file:
    path: "{{ node_config_directory }}/neutron-uplugin-agent"
    state: "directory"
  when: inventory_hostname in groups['neutron-uplugin-agent']

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ uplugin_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0770"
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ uplugin_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over neutron.conf
  become: true
  vars:
    neutron_uplugin_agent: "{{ uplugin_services['neutron-uplugin-agent'] }}"
  merge_configs:
    sources:
      - "/usr/share/kolla-ansible/ansible/roles/neutron/templates/neutron.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/neutron.conf"
      - "{{ node_custom_config }}/neutron/{{ item }}.conf"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/neutron-uplugin-agent/neutron.conf"
    mode: "0660"
  when:
    - neutron_uplugin_agent.enabled | bool
    - neutron_uplugin_agent.host_in_groups | bool
    - inventory_hostname in groups['neutron-uplugin-agent']
  loop:
    - neutron-server
    - neutron-openvswitch-agent
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-l3-agent
    - neutron-metadata-agent
  notify:
    - "Restart neutron-uplugin-agent container"

- name: Copying over neutron-uplugin-agent.conf
  become: true
  vars:
    neutron_uplugin_agent: "{{ uplugin_services['neutron-uplugin-agent'] }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/neutron-uplugin-agent.conf.j2"
      - "{{ node_custom_config }}/neutron/neutron-uplugin-agent.conf"
    dest: "{{ node_config_directory }}/neutron-uplugin-agent/neutron-uplugin-agent.conf"
    mode: "0660"
  when:
    - neutron_uplugin_agent.enabled | bool
    - neutron_uplugin_agent.host_in_groups | bool
    - inventory_hostname in groups['neutron-uplugin-agent']
  notify:
    - "Restart neutron-uplugin-agent container"
