---
- include_role:
    name: rabbitmq
    tasks_from: config
  vars:
    role_rabbitmq_cluster_cookie: "{{ rabbitmq_cluster_cookie }}"
    role_rabbitmq_cluster_port: "{{ rabbitmq_cluster_port }}"
    role_rabbitmq_epmd_port: "{{ rabbitmq_epmd_port }}"
    role_rabbitmq_groups: rabbitmq
    role_rabbitmq_management_port: "{{ rabbitmq_management_port }}"
    role_rabbitmq_monitoring_password: "{{ rabbitmq_monitoring_password }}"
    role_rabbitmq_monitoring_user: "{{ rabbitmq_monitoring_user }}"
    role_rabbitmq_password: "{{ rabbitmq_password }}"
    role_rabbitmq_port: "{{ rabbitmq_port }}"
    role_rabbitmq_user: "{{ rabbitmq_user }}"
    role_rabbitmq_prometheus_port: "{{ rabbitmq_prometheus_port }}"
    kolla_action: "config"

- name: Replace rabbitmq executable to pacemaker remote
  vars:
    service_name: "rabbitmq"
  replace:
    path: "{{ node_config_directory }}/{{ service_name }}/config.json"
    regexp: "rabbitmq-server"
    replace: "pacemaker-remoted -l /var/log/kolla/rabbitmq/pacemaker-remote.log"

- import_tasks: config-pacemaker-resource.yml
