---
- name: Get container facts
  kolla_container_facts:
    name:
      - malphite
  register: container_facts

- name: Checking free port for nuntius
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ malphite_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['malphite'] is not defined
    - inventory_hostname in groups['malphite']
