---
- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: directory
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ nuntius_services }}"

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ nuntius_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0770"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ nuntius_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over nuntius notifications.tmpl file
  become: true
  vars:
    service_name: "nuntius"
    service: "{{ nuntius_services[service_name]}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/nuntius/notifications.tmpl"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/nuntius/{{ inventory_hostname }}/notifications.tmpl.j2"
    - "{{ node_custom_config }}/nuntius/notifications.tmpl.j2"
    - "{{ role_path }}/templates/notifications.tmpl.j2"
  notify:
    - Restart nuntius container

- name: Copying over nuntius nuntius.yml file
  become: true
  vars:
    service_name: "nuntius"
    service: "{{ nuntius_services[service_name]}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/nuntius/nuntius.yml"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/nuntius/{{ inventory_hostname }}/nuntius.yml.j2"
    - "{{ node_custom_config }}/nuntius/nuntius.yml.j2"
    - "{{ role_path }}/templates/nuntius.yml.j2"
  notify:
    - Restart nuntius container
