---
- name: Ensuring config directories exist
  vars:
    service_name: "{{ item.0.service_name }}"
    service: "{{ maine_common_services[service_name] }}"
  file:
    path: "{{ node_config_directory }}/{{ item.1 }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  with_subelements:
    - - service_name: "cron"
        paths:
          - "cron"
          - "cron/logrotate"
      - service_name: "maine-toolbox"
        paths:
          - "maine-toolbox"
    - paths
  when: service | service_enabled_and_mapped_to_host

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ maine_common_services }}"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when: item.value | service_enabled_and_mapped_to_host
  with_dict: "{{ maine_common_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying admin-openrc for maine-toolbox service
  vars:
    service_name: "maine-toolbox"
    service: "{{ maine_common_services[service_name] }}"
  template:
    src: "admin-openrc.sh.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/admin-openrc"
    mode: "0755"
  become: true
  when: service | service_enabled_and_mapped_to_host
  notify:
    - "Restart {{ service_name }} container"

- name: Copying service logrotate config file
  vars:
    cron_logrotate_enabled_services: >-
      {{ cron_logrotate_services |
         selectattr('enabled') |
         map(attribute='name') |
         list }}
    service_name: "{{ item }}"
  template:
    src: "cron-logrotate-global.conf.j2"
    dest: "{{ node_config_directory }}/cron/logrotate.conf"
    mode: "0660"
  become: true
  when:
    - maine_common_services.cron | service_enabled_and_mapped_to_host
  notify:
    - Restart cron container

- name: Remove legacy cron container
  become: true
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items: "{{  deprecated_maine_common_services }}"
