---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ shadowfiend_services }}"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: shadowfiend_policy
  with_first_found:
    - files: "{{ supported_policy_format_list }}"
      paths:
        - "{{ node_custom_config }}/shadowfiend/"
      skip: true

- name: Set shadowfiend policy file
  set_fact:
    shadowfiend_policy_file: "{{ shadowfiend_policy.results.0.stat.path | basename }}"
    shadowfiend_policy_file_path: "{{ shadowfiend_policy.results.0.stat.path }}"
  when:
    - shadowfiend_policy.results

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ shadowfiend_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ shadowfiend_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over existing policy file
  template:
    src: "{{ shadowfiend_policy_file_path }}"
    dest: "{{ node_config_directory }}/{{ item.key }}/{{ shadowfiend_policy_file }}"
    mode: "0660"
  become: true
  when:
    - shadowfiend_policy_file is defined
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ shadowfiend_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over shadowfiend.conf
  vars:
    service_name: "{{ item.key }}"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/shadowfiend.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/shadowfiend.conf"
      - "{{ node_custom_config }}/shadowfiend/{{ item.key }}.conf"
      - "{{ node_custom_config }}/shadowfiend/{{ inventory_hostname }}/shadowfiend.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/shadowfiend.conf"
    mode: "0660"
  become: true
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ shadowfiend_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over wsgi-shadowfiend files for services
  vars:
    service: "{{ shadowfiend_services['shadowfiend-api']}}"
  template:
    src: "wsgi-shadowfiend.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/wsgi-shadowfiend.conf"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_items:
    - "shadowfiend-api"
  notify:
    - Restart shadowfiend-api container

- name: Copying over email.j2
  vars:
    service_name: "shadowfiend-processor"
    service: "{{ shadowfiend_services[service_name] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/email.j2"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - files:
        - "{{ node_custom_config }}/shadowfiend/{{ inventory_hostname }}/email.j2"
        - "{{ node_custom_config }}/shadowfiend/email.j2"
      skip: true
  notify:
    - Restart shadowfiend-processor container

- name: Copying over sms.j2
  vars:
    service_name: "shadowfiend-processor"
    service: "{{ shadowfiend_services[service_name] }}"
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/sms.j2"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - files:
        - "{{ node_custom_config }}/shadowfiend/{{ inventory_hostname }}/sms.j2"
        - "{{ node_custom_config }}/shadowfiend/sms.j2"
      skip: true
  notify:
    - Restart shadowfiend-processor container
