---
- name: Pulling shadowfiend images
  become: true
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ item.value.image }}"
  with_dict: "{{ shadowfiend_services }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
