---
- name: Cleanup legacy config files
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: absent
  loop: "{{ deprecated_prometheus_services }}"

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_services }}"

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ prometheus_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_services }}"
  notify:
    - Restart {{ item.key }} container

- name: Copying over prometheus config file
  vars:
    service: "{{ prometheus_services['prometheus-server']}}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/prometheus-server/prometheus.yml"
    mode: "0660"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  with_first_found:
    - "{{ node_custom_config }}/prometheus/{{ inventory_hostname }}/prometheus.yml"
    - "{{ node_custom_config }}/prometheus/prometheus.yml"
    - "{{ role_path }}/templates/prometheus.yml.j2"
  notify:
    - Restart prometheus-server container

- name: Copying over prometheus_proxy.conf for prometheus-proxy
  vars:
    service: "{{ prometheus_services['prometheus-proxy'] }}"
  template:
    src: "prometheus_proxy.conf.j2"
    dest: "{{ node_config_directory }}/prometheus-proxy/prometheus_proxy.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart prometheus-proxy container

- name: Copying over wsgi-prometheus-proxy.conf for prometheus-proxy
  vars:
    service: "{{ prometheus_services['prometheus-proxy'] }}"
  template:
    src: "wsgi-prometheus-proxy.conf.j2"
    dest: "{{ node_config_directory }}/prometheus-proxy/wsgi-prometheus-proxy.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart prometheus-proxy container
