---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ ryze_services }}"

- name: Ensuring logo directories exist
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  file:
    path: "{{ node_config_directory }}/{{ service_name }}/logo"
    state: directory
    mode: "0660"
  become: true
  register: ryze_logo_directory
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool

- name: Check if generic shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: generic_stat
  with_first_found:
    - files: "{{ ryze_logo.generic }}"
      paths:
        - "{{ node_custom_config }}/ryze/"
      skip: true

- name: Check if navbar shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: navbar_stat
  with_first_found:
    - files: "{{ ryze_logo.navbar }}"
      paths:
        - "{{ node_custom_config }}/ryze/"
      skip: true

- name: Check if favicon shall be overwritten
  local_action: stat path="{{ item }}"
  run_once: True
  register: favicon_stat
  with_first_found:
    - files: "{{ ryze_logo.favicon }}"
      paths:
        - "{{ node_custom_config }}/ryze/"
      skip: true

- name: Set generic logo file
  set_fact:
    ryze_generic_logo_file: "{{ ryze_logo.generic }}"
  when:
    - generic_stat.results

- name: Set navbar logo file
  set_fact:
    ryze_navbar_logo_file: "{{ ryze_logo.navbar }}"
  when:
    - navbar_stat.results

- name: Set favicon logo file
  set_fact:
    ryze_favicon_logo_file: "{{ ryze_logo.favicon }}"
  when:
    - favicon_stat.results

- name: Copying over existing generic logo file
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  become: true
  copy:
    src: "{{ node_custom_config }}/{{ service_name }}/{{ ryze_logo.generic }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/logo/{{ ryze_logo.generic }}"
  when:
    - ryze_generic_logo_file is defined
    - inventory_hostname in groups[service.group]

- name: Copying over existing navbar logo file
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  become: true
  copy:
    src: "{{ node_custom_config }}/{{ service_name }}/{{ ryze_logo.navbar }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/logo/{{ ryze_logo.navbar }}"
  when:
    - ryze_navbar_logo_file is defined
    - inventory_hostname in groups[service.group]

- name: Copying over existing favicon logo file
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  become: true
  copy:
    src: "{{ node_custom_config }}/{{ service_name }}/{{ ryze_logo.favicon }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/logo/{{ ryze_logo.favicon }}"
  when:
    - ryze_favicon_logo_file is defined
    - inventory_hostname in groups[service.group]

- name: Copying ryze ryze.prod.json to "{{ node_config_directory }}"
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  template:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/ryze.prod.json"
    mode: "0660"
  become: true
  register: ryze_conf
  with_first_found:
    - "{{ node_custom_config }}/{{ service_name }}/{{ inventory_hostname }}/ryze.prod.json.j2"
    - "{{ node_custom_config }}/{{ service_name }}/ryze.prod.json.j2"
    - "{{ role_path }}/templates/ryze.prod.json.j2"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart ryze container

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ ryze_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  template:
    src: "{{ service_name }}.json.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/config.json"
    mode: "0660"
  become: true
  register: ryze_config_json
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart ryze container
