---
- name: Remove ryze container instances
  vars:
    service_name: "ryze"
    service: "{{ ryze_services[service_name] }}"
  become: true
  docker_container:
    name: "{{ item.value.container_name }}"
    state: absent
  with_dict: "{{ ryze_services }}"
  when:
    - inventory_hostname in groups[service.group]
  tags: ryze
