---
- name: Get container facts
  kolla_container_facts:
    name:
      - ryze
  register: container_facts

- name: Checking free port for Ryze
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ ryze_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['ryze'] is not defined
    - inventory_hostname in groups['ryze']
