---
- name: Apply role chrony
  gather_facts: true
  hosts:
    - chrony
    - chrony-server
  serial: '{{ kolla_serial|default("0") }}'
  vars:
    source_dir: "/usr/share/maine-ansible/config/chrony"
    dest_dir: "/etc"
  tasks:
    - name: Install chrony package
      package:
        name: chrony
        state: present
      become: True

    - name: Copying over ha chrony.conf
      template:
        src: "{{ source_dir }}/chrony-ha.conf.j2"
        dest: "{{ dest_dir }}/chrony.conf"
        mode: "0660"
      become: True

    - name: Enable and restart chrony service
      systemd:
        name: chronyd
        state: restarted
        enabled: yes
      become: True
