---
- name: Create cron jobs
  hosts:
    - localhost
  gather_facts: false
  become: true
  tags: cron
  tasks:
    - name: Creates a maine backup cron job
      cron:
        name: "maine backup"
        minute: "0"
        hour: "0"
        weekday: "0"
        job: "maine-ansible maine_backup"

    - name: Creates a mariadb full backup cron job
      cron:
        name: "mariadb full backup"
        minute: "0"
        hour: "0"
        weekday: "0"
        job: "maine-ansible mariadb_backup"

    - name: Creates a mariadb incremental backup cron job
      cron:
        name: "mariadb incremental backup"
        minute: "0"
        hour: "1"
        job: "maine-ansible mariadb_backup --incremental"

    - name: Creates a cleanup backup cron job
      cron:
        name: "cleanup backup"
        minute: "0"
        hour: "2"
        job: "maine-ansible cleanup_backup"
