---
- import_playbook: /usr/share/kolla-ansible/ansible/gather-facts.yml

- name: Apply role host
  hosts: baremetal
  gather_facts: no
  vars:
    customize_etc_hosts: True
  tasks:
    - name: Ensure localhost in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "^127.0.0.1.*"
        line: "127.0.0.1 localhost"
        state: present
      become: True
      when: customize_etc_hosts | bool

    - name: Generate /etc/hosts for all of the nodes
      blockinfile:
        dest: /etc/hosts
        marker: "# {mark} ANSIBLE GENERATED HOSTS"
        block: |
            {% for host in groups['baremetal'] %}
            {% set hostname = hostvars[host]['ansible_hostname'] %}
            {% set api_interface = hostvars[host]['api_interface']|replace('-', '_') %}
            {% set network_interface = hostvars[host]['network_interface']|replace('-', '_') %}
            {% set storage_interface = hostvars[host]['storage_interface']|replace('-', '_') %}
            {% set tunnel_interface = hostvars[host]['tunnel_interface']|replace('-', '_') %}

            ## For Nova Live Migration
            {% if 'ansible_' + api_interface in hostvars[host] %}
            {{ 'api' | kolla_address(host) | put_address_in_context('url') }} {{ hostvars[host]['ansible_nodename'] }} {{ hostvars[host]['ansible_hostname'] }}
            {% endif %}

            ## For Masakari Host HA
            {% if 'ansible_' + network_interface in hostvars[host] %}
            {{ 'network' | kolla_address(host) | put_address_in_context('url') }} {{ hostvars[host]['ansible_hostname'] }}.external
            {% endif %}
            {% if 'ansible_' + api_interface in hostvars[host] %}
            {{ 'api' | kolla_address(host) | put_address_in_context('url') }} {{ hostvars[host]['ansible_hostname'] }}.internal
            {% endif %}
            {% if 'ansible_' + storage_interface in hostvars[host] %}
            {{ 'storage' | kolla_address(host) | put_address_in_context('url') }} {{ hostvars[host]['ansible_hostname'] }}.storage
            {% endif %}
            {% if 'ansible_' + tunnel_interface in hostvars[host] %}
            {{ 'tunnel' | kolla_address(host) | put_address_in_context('url') }} {{ hostvars[host]['ansible_hostname'] }}.tenant
            {% endif %}
            {% endfor %}
      become: True
      register: hosts_file
      when:
        - customize_etc_hosts | bool
        - inventory_hostname not in groups['bifrost'] or
          'ansible_' + hostvars[inventory_hostname]['api_interface'] in hostvars[inventory_hostname]

    - name: Restart OpenStack Services who use /etc/hosts
      shell:
        for i in `docker ps | grep {{ item }} | awk '{print $1}'`;do docker restart $i;done
      become: True
      with_items:
        - kolla_toolbox
        - nova_compute
        - nova_libvirt
        - nova_ssh
        - masakari_hostmonitor
      when: hosts_file is changed
