---
- name: Openstack configuration sanity check
  gather_facts: false
  hosts: maine_all
  tasks:
    - name: Check openstack_release
      fail:
        msg: "openstack_release,
          openstack_aggressive_release must
          be manually configured in
          /etc/maine/globals.yml
          and is forbidden to configure auto"
      when: >
        openstack_release is none or
        openstack_release == "auto" or
        openstack_aggressive_release is none

    - name: Check openstack interface
      fail:
        msg: "api_interface, tunnel_interface,
          network_interface, neutron_external_interface,
          kolla_internal_vip_address,
          kolla_external_vip_address must be manually
          configured in /etc/maine/kolla-extra-globals.yml"
      when: >
        api_interface is none or
        tunnel_interface is none or
        network_interface is none or
        neutron_external_interface is none or
        kolla_internal_vip_address is none or
        kolla_external_vip_address is none

    - name: Check octavia network vars manually defined
      fail:
        msg: "octavia_amp_network, octavia_network_interface
          must be manually configured in /etc/maine/kolla-extra-globals.yml"
      when:
        - enable_octavia | bool
        - octavia_network_type != 'tenant'
        - octavia_network_interface is not defined or octavia_amp_network is not defined
