---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ lulu_services }}"

- name: Copying lulu config.prod.js to "{{ node_config_directory }}"
  template:
    src: "config.prod.js.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.prod.js"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ lulu_services }}"
  notify:
    - Restart lulu container

- name: Copying over extra CA certificates
  become: true
  copy:
    src: "{{ node_config }}/certificates/ca/"
    dest: "{{ node_config_directory }}/{{ item.key }}/ca-certificates"
    mode: "0644"
  when:
    - item.value.enabled | bool
    - inventory_hostname in groups[item.value.group]
    - kolla_copy_ca_into_containers | bool
  with_dict: "{{ lulu_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over config.json files for services
  vars:
    service_name: "lulu"
    service: "{{ lulu_services[service_name] }}"
  template:
    src: "{{ service_name }}.json.j2"
    dest: "{{ node_config_directory }}/{{ service_name }}/config.json"
    mode: "0660"
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
  notify:
    - Restart lulu container
