---
- name: Get container facts
  kolla_container_facts:
    name:
      - lulu
  register: container_facts

- name: Checking free port for Lulu
  wait_for:
    host: "{{ api_interface_address }}"
    port: "{{ lulu_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - container_facts['lulu'] is not defined
    - inventory_hostname in groups['lulu']
