---
- import_tasks: config.yml

- include_tasks: register.yml
  when: inventory_hostname in groups['lulu']

- import_tasks: check-containers.yml

- import_tasks: bootstrap_service.yml

- name: Flush handlers
  meta: flush_handlers
