---
groups:
- name: RabbitmqAlerts
  rules:
    - alert: RabbitmqNodeDown
      expr: sum(rabbitmq_build_info) < 3
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Rabbitmq 节点down (instance {{ $labels.instance }})
        description: "RabbitMQ 集群中运行的节点少于 3 个  当前数量为: {{ $value }}"
    - alert: RabbitmqNodeNotDistributed
      expr: erlang_vm_dist_node_state < 3
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: Rabbitmq 节点未分发 (instance {{ $labels.instance }})
        description: "节点 {{ $labels.instance }} 分发链接状态未启用 "
    - alert: RabbitmqMemoryHigh
      expr: rabbitmq_process_resident_memory_bytes / rabbitmq_resident_memory_limit_bytes * 100 > 90
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Rabbitmq 内存使用过高 (instance {{ $labels.instance }})
        description: "节点 {{ $labels.instance }} 使用超过 90% 的已分配内存,当前值为: {{ $value }}"
    - alert: RabbitmqTooManyUnackMessages
      expr: sum(rabbitmq_queue_messages_unacked) BY (queue) > 1000
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Rabbitmq 太多未确认消息 (instance {{ $labels.instance }})
        description: "Rabbitmq 太多未确认消息，当前未确认消息数为： {{ $value }}"
    - alert: RabbitmqTooManyConnections
      expr: rabbitmq_connections > 1000
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Rabbitmq 连接数过多 (instance {{ $labels.instance }})
        description: "节点{{ $labels.instance }}的总连接数太高,当前连接数为：{{ $value }}"
    - alert: RabbitmqNoQueueConsumer
      expr: rabbitmq_queue_consumers < 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Rabbitmq 缺少队列消费者 (instance {{ $labels.instance }})
        description: "Rabbitmq 队列的消费者小于1"
    - alert: RabbitmqUnroutableMessages
      expr: increase(rabbitmq_channel_messages_unroutable_returned_total[1m]) > 0 or increase(rabbitmq_channel_messages_unroutable_dropped_total[1m]) > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Rabbitmq 不可路由消息 (instance {{ $labels.instance }})
        description: "Rabbitmq 存在不可路由消息,数量为：{{ $value }}"
